### ISSUE TITLE
Restrict the pointer head

### ISSUE THREAD

**Issue by pAditya198** [AmanRaj1608/Sketch#18]
Try restricting the pointer head from going out of the canvas or you can if possible make it come around from the other side for example if I try to take it out from the top it comes inside from the bottom something like that

**Comment by AmanRaj1608** [comment]
Will do 🙇🏻‍♂️

**Comment by sanjay270899** [comment]
Can I work on this? @AmanRaj1608

**Comment by AmanRaj1608** [comment]
Sure @sanjay270899 GFI 🤗👍🏻

**Comment by sanjay270899** [comment]
Done.
Here is the video that shows how it looks after changes.
https://drive.google.com/file/d/1SMM5_m0kNur6_soMSPEZISA0zKAvZRFw/view?usp=sharing

**Comment by sanjay270899** [comment]
Is that solution in the above video okay? @AmanRaj1608

**Comment by AmanRaj1608** [comment]
Yes @sanjay270899 , 
This solves the problem.
Really appreciate this 🙌🏻

**Comment by sanjay270899** [comment]
Thanks, @AmanRaj1608. Should I send PR now? What should be the title of PR? Any format?

**Comment by AmanRaj1608** [comment]
Yes create a PR with any suitable title, 
not following any contribute guide right now for this project 😅
