### ISSUE TITLE
Pointer gets invisible after clicking on "clear it!" button.

### ISSUE THREAD

**Issue by sanjay270899** [AmanRaj1608/Sketch#34]
On clicking on the "clear it!" button, the pointer gets invisible. Pointer gets visible only after pressing the up, down, left, or right key.
Now, this issue can have two solutions:
1.) All the drawings will be cleared but the last position of the pointer should be visible.
OR
2.) All the drawings will be cleared and then a new random position of the pointer will be assigned, which should be visible.

**Comment by AmanRaj1608** [comment]
I guess 2nd point makes sense as if we display the last point and then start drawing then it will not look right.

**Comment by sanjay270899** [comment]
Can I solve this? @AmanRaj1608

**Comment by AmanRaj1608** [comment]
Yes sure create a PR 👍🏻
